import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { useForm, useWatch } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Link, useLocation } from "wouter";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Separator } from "@/components/ui/separator";
import { 
  Plus, Building2, Trash2, FileText, Users, Calendar, 
  ChevronRight, Search, Filter, Eye, Edit, AlertTriangle,
  CheckCircle2, Clock, XCircle, MapPin, Hash
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { insertLLCSchema, type LLC } from "@shared/schema";
import { generateLLCName, canEditLLCName } from "@/lib/llcUtils";

const US_STATES = [
  { code: "DE", name: "Delaware" },
  { code: "CA", name: "California" },
  { code: "TX", name: "Texas" },
  { code: "NY", name: "New York" },
  { code: "FL", name: "Florida" },
  { code: "NV", name: "Nevada" },
  { code: "WY", name: "Wyoming" },
  { code: "AZ", name: "Arizona" },
  { code: "CO", name: "Colorado" },
  { code: "WA", name: "Washington" },
];

const llcFormSchema = z.object({
  projectAddress: z.string().min(1, "Project address is required"),
  projectName: z.string().min(1, "Project name is required"),
  name: z.string().optional(),
  nameManuallyEdited: z.boolean().default(false),
  status: z.enum(["forming", "active", "closed"]).default("forming"),
  stateOfFormation: z.string().default("Delaware"),
  einNumber: z.string().optional(),
  registeredAgent: z.string().optional(),
  registeredAgentAddress: z.string().optional(),
  formationDate: z.string().optional(),
  address: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  zip: z.string().optional(),
  members: z.string().optional(),
  annualReportDueDate: z.string().optional(),
  annualReportStatus: z.enum(["pending", "filed", "overdue"]).default("pending"),
});

type LLCFormValues = z.infer<typeof llcFormSchema>;

export default function LLCAdmin() {
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [selectedLLC, setSelectedLLC] = useState<LLC | null>(null);
  const [statusFilter, setStatusFilter] = useState<string>("all");
  const [searchTerm, setSearchTerm] = useState("");
  const { toast } = useToast();
  const [, setLocation] = useLocation();

  const form = useForm<LLCFormValues>({
    resolver: zodResolver(llcFormSchema),
    defaultValues: {
      projectAddress: "",
      projectName: "",
      name: "",
      nameManuallyEdited: false,
      status: "forming",
      stateOfFormation: "Delaware",
      einNumber: "",
      registeredAgent: "",
      registeredAgentAddress: "",
      formationDate: "",
      address: "",
      city: "",
      state: "",
      zip: "",
      members: "",
      annualReportDueDate: "",
      annualReportStatus: "pending",
    },
  });

  const projectAddress = useWatch({ control: form.control, name: "projectAddress" });
  const nameManuallyEdited = useWatch({ control: form.control, name: "nameManuallyEdited" });
  const currentName = useWatch({ control: form.control, name: "name" });

  const autoGeneratedName = projectAddress ? generateLLCName(projectAddress) : "";
  
  const displayName = nameManuallyEdited && currentName ? currentName : autoGeneratedName;

  const { data: llcs = [], isLoading } = useQuery<LLC[]>({
    queryKey: ["/api/llcs"],
  });

  const filteredLLCs = llcs.filter((llc) => {
    const matchesStatus = statusFilter === "all" || llc.status === statusFilter;
    const matchesSearch = searchTerm === "" || 
      llc.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      llc.projectName.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesStatus && matchesSearch;
  });

  const stats = {
    total: llcs.length,
    forming: llcs.filter(l => l.status === "forming").length,
    active: llcs.filter(l => l.status === "active").length,
    closed: llcs.filter(l => l.status === "closed").length,
  };

  const createMutation = useMutation({
    mutationFn: async (data: LLCFormValues) => {
      const llcName = data.nameManuallyEdited && data.name 
        ? data.name 
        : generateLLCName(data.projectAddress);
      const payload = {
        ...data,
        name: llcName,
        address: data.projectAddress,
      };
      const response = await apiRequest("POST", "/api/llcs", payload);
      return response.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/llcs"] });
      queryClient.invalidateQueries({ queryKey: ["/api/dashboard/stats"] });
      setIsCreateOpen(false);
      form.reset();
      toast({
        title: "LLC Created",
        description: "The new LLC has been created successfully.",
      });
    },
    onError: () => {
      toast({
        title: "Error",
        description: "Failed to create LLC. Please try again.",
        variant: "destructive",
      });
    },
  });

  const deleteMutation = useMutation({
    mutationFn: async (id: number) => {
      await apiRequest("DELETE", `/api/llcs/${id}`);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/llcs"] });
      queryClient.invalidateQueries({ queryKey: ["/api/dashboard/stats"] });
      setSelectedLLC(null);
      toast({
        title: "LLC Deleted",
        description: "The LLC has been deleted successfully.",
      });
    },
    onError: () => {
      toast({
        title: "Error",
        description: "Failed to delete LLC. Please try again.",
        variant: "destructive",
      });
    },
  });

  const updateMutation = useMutation({
    mutationFn: async ({ id, data }: { id: number; data: Partial<LLC> }) => {
      const response = await apiRequest("PATCH", `/api/llcs/${id}`, data);
      return response.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/llcs"] });
      toast({
        title: "LLC Updated",
        description: "The LLC has been updated successfully.",
      });
    },
    onError: () => {
      toast({
        title: "Error",
        description: "Failed to update LLC. Please try again.",
        variant: "destructive",
      });
    },
  });

  const onSubmit = (data: LLCFormValues) => {
    createMutation.mutate(data);
  };

  return (
    <div className="flex-1 p-6 md:p-8">
      <div className="flex items-center justify-between mb-6 flex-wrap gap-4">
        <div>
          <h1 className="text-2xl font-semibold text-foreground" data-testid="text-page-title">
            LLC Administration
          </h1>
          <p className="text-sm text-muted-foreground mt-1">
            Manage project-specific LLCs and track compliance
          </p>
        </div>
        
        <Dialog open={isCreateOpen} onOpenChange={(open) => {
          setIsCreateOpen(open);
          if (!open) form.reset();
        }}>
          <DialogTrigger asChild>
            <Button data-testid="button-new-llc">
              <Plus className="h-4 w-4 mr-2" />
              Create LLC
            </Button>
          </DialogTrigger>
          <DialogContent className="sm:max-w-[600px] max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle>Create New Project LLC</DialogTitle>
              <DialogDescription>
                Create a new child LLC entity for a construction project. The LLC name will be auto-generated.
              </DialogDescription>
            </DialogHeader>
            <Form {...form}>
              <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
                <div className="space-y-4">
                  <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wide">
                    Project Information
                  </h3>
                  
                  <FormField
                    control={form.control}
                    name="projectName"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Project Name <span className="text-destructive">*</span></FormLabel>
                        <FormControl>
                          <Input placeholder="e.g., Smith Residence" data-testid="input-project-name" {...field} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="projectAddress"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Project Address <span className="text-destructive">*</span></FormLabel>
                        <FormControl>
                          <Input placeholder="e.g., 123 Oak Street" data-testid="input-project-address" {...field} />
                        </FormControl>
                        <FormDescription>Used to generate the LLC name</FormDescription>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <div className="p-3 bg-primary/5 border border-primary/20 rounded-md space-y-2">
                    <div className="flex items-center justify-between">
                      <p className="text-xs text-muted-foreground">LLC Name:</p>
                      {!nameManuallyEdited && (
                        <Button 
                          type="button" 
                          variant="ghost" 
                          size="sm"
                          className="h-6 text-xs"
                          onClick={() => {
                            form.setValue("nameManuallyEdited", true);
                            form.setValue("name", autoGeneratedName);
                          }}
                          data-testid="button-edit-llc-name"
                        >
                          <Edit className="h-3 w-3 mr-1" />
                          Edit
                        </Button>
                      )}
                    </div>
                    {nameManuallyEdited ? (
                      <div className="flex gap-2">
                        <Input
                          value={currentName || ""}
                          onChange={(e) => form.setValue("name", e.target.value)}
                          placeholder="Enter LLC name"
                          data-testid="input-llc-name"
                        />
                        <Button
                          type="button"
                          variant="outline"
                          size="sm"
                          onClick={() => {
                            form.setValue("nameManuallyEdited", false);
                            form.setValue("name", "");
                          }}
                          data-testid="button-reset-llc-name"
                        >
                          Reset
                        </Button>
                      </div>
                    ) : (
                      <p className="font-medium text-primary" data-testid="text-generated-name">
                        {displayName || "Enter project address to generate"}
                      </p>
                    )}
                  </div>
                </div>

                <Separator />

                <div className="space-y-4">
                  <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wide">
                    Formation Details
                  </h3>
                  
                  <div className="grid grid-cols-2 gap-4">
                    <FormField
                      control={form.control}
                      name="stateOfFormation"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>State of Formation</FormLabel>
                          <Select onValueChange={field.onChange} value={field.value}>
                            <FormControl>
                              <SelectTrigger data-testid="select-state">
                                <SelectValue placeholder="Select state" />
                              </SelectTrigger>
                            </FormControl>
                            <SelectContent>
                              {US_STATES.map((state) => (
                                <SelectItem key={state.code} value={state.name}>
                                  {state.name}
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                    <FormField
                      control={form.control}
                      name="status"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Status</FormLabel>
                          <Select onValueChange={field.onChange} value={field.value}>
                            <FormControl>
                              <SelectTrigger data-testid="select-status">
                                <SelectValue placeholder="Select status" />
                              </SelectTrigger>
                            </FormControl>
                            <SelectContent>
                              <SelectItem value="forming">Forming</SelectItem>
                              <SelectItem value="active">Active</SelectItem>
                              <SelectItem value="closed">Closed</SelectItem>
                            </SelectContent>
                          </Select>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <FormField
                      control={form.control}
                      name="einNumber"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>EIN Number</FormLabel>
                          <FormControl>
                            <Input placeholder="XX-XXXXXXX" data-testid="input-ein" {...field} />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                    <FormField
                      control={form.control}
                      name="formationDate"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Formation Date</FormLabel>
                          <FormControl>
                            <Input type="date" data-testid="input-formation-date" {...field} />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  </div>
                </div>

                <Separator />

                <div className="space-y-4">
                  <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wide">
                    Registered Agent
                  </h3>
                  
                  <FormField
                    control={form.control}
                    name="registeredAgent"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Registered Agent Name</FormLabel>
                        <FormControl>
                          <Input placeholder="e.g., Corporation Service Company" data-testid="input-registered-agent" {...field} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="registeredAgentAddress"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Registered Agent Address</FormLabel>
                        <FormControl>
                          <Textarea placeholder="Full address" data-testid="input-registered-agent-address" {...field} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>

                <DialogFooter>
                  <Button 
                    type="button"
                    variant="outline"
                    onClick={() => setIsCreateOpen(false)}
                  >
                    Cancel
                  </Button>
                  <Button 
                    type="submit" 
                    disabled={createMutation.isPending || !displayName}
                    data-testid="button-submit-llc"
                  >
                    {createMutation.isPending ? "Creating..." : "Create LLC"}
                  </Button>
                </DialogFooter>
              </form>
            </Form>
          </DialogContent>
        </Dialog>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
        <Card className="hover-elevate cursor-pointer" onClick={() => setStatusFilter("all")} data-testid="card-stat-total">
          <CardContent className="p-4">
            <div className="flex items-center justify-between gap-2">
              <div>
                <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Total LLCs</p>
                <p className="text-2xl font-bold mt-1">{stats.total}</p>
              </div>
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
                <Building2 className="h-5 w-5 text-primary" />
              </div>
            </div>
          </CardContent>
        </Card>
        <Card className={`hover-elevate cursor-pointer ${statusFilter === 'forming' ? 'ring-2 ring-primary' : ''}`} onClick={() => setStatusFilter("forming")} data-testid="card-stat-forming">
          <CardContent className="p-4">
            <div className="flex items-center justify-between gap-2">
              <div>
                <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Forming</p>
                <p className="text-2xl font-bold mt-1">{stats.forming}</p>
              </div>
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-amber-500/10">
                <Clock className="h-5 w-5 text-amber-500" />
              </div>
            </div>
          </CardContent>
        </Card>
        <Card className={`hover-elevate cursor-pointer ${statusFilter === 'active' ? 'ring-2 ring-primary' : ''}`} onClick={() => setStatusFilter("active")} data-testid="card-stat-active">
          <CardContent className="p-4">
            <div className="flex items-center justify-between gap-2">
              <div>
                <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Active</p>
                <p className="text-2xl font-bold mt-1">{stats.active}</p>
              </div>
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-emerald-500/10">
                <CheckCircle2 className="h-5 w-5 text-emerald-500" />
              </div>
            </div>
          </CardContent>
        </Card>
        <Card className={`hover-elevate cursor-pointer ${statusFilter === 'closed' ? 'ring-2 ring-primary' : ''}`} onClick={() => setStatusFilter("closed")} data-testid="card-stat-closed">
          <CardContent className="p-4">
            <div className="flex items-center justify-between gap-2">
              <div>
                <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Closed</p>
                <p className="text-2xl font-bold mt-1">{stats.closed}</p>
              </div>
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-muted">
                <XCircle className="h-5 w-5 text-muted-foreground" />
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2">
          <Card data-testid="card-llc-list">
            <CardHeader className="pb-3">
              <div className="flex items-center justify-between gap-4 flex-wrap">
                <CardTitle className="text-lg">Project LLCs</CardTitle>
                <div className="flex items-center gap-2">
                  <div className="relative">
                    <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                    <Input
                      placeholder="Search LLCs..."
                      value={searchTerm}
                      onChange={(e) => setSearchTerm(e.target.value)}
                      className="pl-8 w-48"
                      data-testid="input-search"
                    />
                  </div>
                  {statusFilter !== "all" && (
                    <Button variant="ghost" size="sm" onClick={() => setStatusFilter("all")}>
                      Clear filter
                    </Button>
                  )}
                </div>
              </div>
            </CardHeader>
            <CardContent className="p-0">
              {isLoading ? (
                <div className="p-4 space-y-4">
                  {[1, 2, 3].map((i) => (
                    <div key={i} className="flex items-center gap-4">
                      <Skeleton className="h-10 w-10 rounded-lg" />
                      <div className="flex-1 space-y-2">
                        <Skeleton className="h-4 w-48" />
                        <Skeleton className="h-3 w-32" />
                      </div>
                      <Skeleton className="h-5 w-20 rounded-full" />
                    </div>
                  ))}
                </div>
              ) : filteredLLCs.length > 0 ? (
                <div className="divide-y">
                  {filteredLLCs.map((llc) => (
                    <div 
                      key={llc.id}
                      className={`flex items-center justify-between gap-4 p-4 hover-elevate cursor-pointer ${
                        selectedLLC?.id === llc.id ? 'bg-accent/50' : ''
                      }`}
                      onClick={() => setSelectedLLC(llc)}
                      data-testid={`row-llc-${llc.id}`}
                    >
                      <div className="flex items-center gap-3 min-w-0">
                        <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-primary/10">
                          <Building2 className="h-5 w-5 text-primary" />
                        </div>
                        <div className="min-w-0">
                          <p className="font-medium truncate">{llc.name}</p>
                          <p className="text-sm text-muted-foreground truncate">{llc.projectName}</p>
                        </div>
                      </div>
                      <div className="flex items-center gap-3 shrink-0">
                        <LLCStatusBadge status={llc.status || "forming"} />
                        <ChevronRight className="h-4 w-4 text-muted-foreground" />
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="py-12 text-center text-muted-foreground">
                  <Building2 className="h-12 w-12 mx-auto mb-4 opacity-50" />
                  <p className="text-sm font-medium">No LLCs found</p>
                  <p className="text-xs mt-1">
                    {searchTerm || statusFilter !== "all" 
                      ? "Try adjusting your search or filter" 
                      : "Create your first LLC to get started"
                    }
                  </p>
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        <div className="lg:col-span-1">
          {selectedLLC ? (
            <LLCDetailPanel 
              llc={selectedLLC} 
              onDelete={() => deleteMutation.mutate(selectedLLC.id)}
              onUpdate={(data) => updateMutation.mutate({ id: selectedLLC.id, data })}
              isDeleting={deleteMutation.isPending}
              onClose={() => setSelectedLLC(null)}
            />
          ) : (
            <Card>
              <CardContent className="p-8 text-center text-muted-foreground">
                <Building2 className="h-12 w-12 mx-auto mb-4 opacity-50" />
                <p className="text-sm font-medium">Select an LLC</p>
                <p className="text-xs mt-1">Click on an LLC to view details</p>
              </CardContent>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
}

interface LLCDetailPanelProps {
  llc: LLC;
  onDelete: () => void;
  onUpdate: (data: Partial<LLC>) => void;
  isDeleting: boolean;
  onClose: () => void;
}

function LLCDetailPanel({ llc, onDelete, onUpdate, isDeleting, onClose }: LLCDetailPanelProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [editData, setEditData] = useState<Partial<LLC>>({});
  
  const handleStatusChange = (newStatus: string) => {
    onUpdate({ status: newStatus });
  };

  const members = llc.members ? JSON.parse(llc.members) : [];

  return (
    <Card data-testid="card-llc-detail">
      <CardHeader className="pb-3">
        <div className="flex items-start justify-between gap-2">
          <div>
            <CardTitle className="text-lg leading-tight">{llc.name}</CardTitle>
            <CardDescription>{llc.projectName}</CardDescription>
          </div>
          <LLCStatusBadge status={llc.status || "forming"} />
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        <Tabs defaultValue="details" className="w-full">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="details" data-testid="tab-details">Details</TabsTrigger>
            <TabsTrigger value="contracts" data-testid="tab-contracts">Contracts</TabsTrigger>
            <TabsTrigger value="compliance" data-testid="tab-compliance">Compliance</TabsTrigger>
          </TabsList>
          
          <TabsContent value="details" className="space-y-4 mt-4">
            <div className="space-y-3">
              <div className="flex items-center gap-2 text-sm">
                <MapPin className="h-4 w-4 text-muted-foreground" />
                <span className="text-muted-foreground">State:</span>
                <span className="font-medium">{llc.stateOfFormation || "Delaware"}</span>
              </div>
              
              {llc.einNumber && (
                <div className="flex items-center gap-2 text-sm">
                  <Hash className="h-4 w-4 text-muted-foreground" />
                  <span className="text-muted-foreground">EIN:</span>
                  <span className="font-medium">{llc.einNumber}</span>
                </div>
              )}
              
              {llc.formationDate && (
                <div className="flex items-center gap-2 text-sm">
                  <Calendar className="h-4 w-4 text-muted-foreground" />
                  <span className="text-muted-foreground">Formed:</span>
                  <span className="font-medium">
                    {new Date(llc.formationDate).toLocaleDateString('en-US', {
                      year: 'numeric',
                      month: 'short',
                      day: 'numeric'
                    })}
                  </span>
                </div>
              )}

              {llc.registeredAgent && (
                <div className="pt-2">
                  <p className="text-xs text-muted-foreground uppercase tracking-wide mb-1">Registered Agent</p>
                  <p className="text-sm font-medium">{llc.registeredAgent}</p>
                  {llc.registeredAgentAddress && (
                    <p className="text-xs text-muted-foreground mt-1">{llc.registeredAgentAddress}</p>
                  )}
                </div>
              )}

              {members.length > 0 && (
                <div className="pt-2">
                  <p className="text-xs text-muted-foreground uppercase tracking-wide mb-2">Members</p>
                  <div className="space-y-2">
                    {members.map((member: { name: string; role: string; percentage: number }, index: number) => (
                      <div key={index} className="flex items-center justify-between text-sm p-2 bg-muted/50 rounded">
                        <div className="flex items-center gap-2">
                          <Users className="h-4 w-4 text-muted-foreground" />
                          <span>{member.name}</span>
                        </div>
                        <span className="text-muted-foreground">{member.percentage}%</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>

            <Separator />

            <div className="space-y-2">
              <p className="text-xs text-muted-foreground uppercase tracking-wide">Change Status</p>
              <Select value={llc.status || "forming"} onValueChange={handleStatusChange}>
                <SelectTrigger data-testid="select-update-status">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="forming">Forming</SelectItem>
                  <SelectItem value="active">Active</SelectItem>
                  <SelectItem value="closed">Closed</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </TabsContent>
          
          <TabsContent value="contracts" className="space-y-4 mt-4">
            <div className="text-center py-6 text-muted-foreground">
              <FileText className="h-8 w-8 mx-auto mb-2 opacity-50" />
              <p className="text-sm">No contracts linked yet</p>
              <p className="text-xs mt-1">Generate contracts using the Contract Builder</p>
              <Link href="/contract-builder">
                <Button variant="outline" size="sm" className="mt-4" data-testid="button-go-to-contracts">
                  Go to Contract Builder
                </Button>
              </Link>
            </div>
          </TabsContent>
          
          <TabsContent value="compliance" className="space-y-4 mt-4">
            <div className="space-y-3">
              <div className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
                <div className="flex items-center gap-2">
                  <Calendar className="h-4 w-4 text-muted-foreground" />
                  <span className="text-sm">Annual Report</span>
                </div>
                <Badge variant={llc.annualReportStatus === "filed" ? "default" : llc.annualReportStatus === "overdue" ? "destructive" : "secondary"}>
                  {llc.annualReportStatus || "Pending"}
                </Badge>
              </div>
              
              {llc.annualReportDueDate && (
                <p className="text-xs text-muted-foreground">
                  Due: {new Date(llc.annualReportDueDate).toLocaleDateString()}
                </p>
              )}
            </div>

            {(llc.status === "active" && (!llc.einNumber || !llc.registeredAgent)) && (
              <div className="p-3 bg-amber-500/10 border border-amber-500/20 rounded-lg">
                <div className="flex items-start gap-2">
                  <AlertTriangle className="h-4 w-4 text-amber-500 mt-0.5" />
                  <div>
                    <p className="text-sm font-medium text-amber-700 dark:text-amber-400">Missing Information</p>
                    <ul className="text-xs text-amber-600 dark:text-amber-500 mt-1 space-y-0.5">
                      {!llc.einNumber && <li>EIN number not recorded</li>}
                      {!llc.registeredAgent && <li>Registered agent not set</li>}
                    </ul>
                  </div>
                </div>
              </div>
            )}
          </TabsContent>
        </Tabs>

        <Separator />

        <div className="flex flex-col gap-2">
          <Link href={`/llc-admin/${llc.id}`}>
            <Button variant="outline" className="w-full" data-testid="button-view-details">
              <Eye className="h-4 w-4 mr-2" />
              View Full Details
            </Button>
          </Link>
          <div className="flex justify-between gap-2">
            <Button 
              variant="ghost" 
              size="sm"
              onClick={onClose}
            >
              Close
            </Button>
            <Button 
              variant="destructive" 
              size="sm"
              onClick={onDelete}
              disabled={isDeleting}
              data-testid="button-delete-llc"
            >
              <Trash2 className="h-4 w-4 mr-1" />
              {isDeleting ? "Deleting..." : "Delete"}
            </Button>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

function LLCStatusBadge({ status }: { status: string }) {
  const statusConfig: Record<string, { label: string; variant: "default" | "secondary" | "destructive" | "outline" }> = {
    forming: { 
      label: "Forming", 
      variant: "secondary"
    },
    active: { 
      label: "Active", 
      variant: "default"
    },
    closed: { 
      label: "Closed", 
      variant: "outline"
    },
    pending: { 
      label: "Pending", 
      variant: "secondary"
    },
    in_formation: { 
      label: "In Formation", 
      variant: "secondary"
    },
    dissolved: { 
      label: "Dissolved", 
      variant: "outline"
    },
  };

  const config = statusConfig[status] || statusConfig.forming;

  return (
    <Badge variant={config.variant} data-testid={`badge-status-${status}`}>
      {config.label}
    </Badge>
  );
}
