CREATE TABLE `child_llcs` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`project_id` integer NOT NULL,
	`legal_name` text NOT NULL,
	`formation_state` text DEFAULT 'Delaware',
	`entity_type` text DEFAULT 'LLC',
	`ein` text,
	`formation_date` text,
	`registered_agent` text,
	`registered_agent_address` text,
	`address` text,
	`city` text,
	`state` text,
	`zip` text,
	`insurance_status` text DEFAULT 'Pending' NOT NULL,
	`insurance_expiration` text,
	`annual_report_due` text,
	FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `clients` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`project_id` integer NOT NULL,
	`legal_name` text NOT NULL,
	`entity_type` text,
	`formation_state` text,
	`address` text,
	`city` text,
	`state` text,
	`zip` text,
	`email` text,
	`phone` text,
	`trust_date` text,
	`trustee_name` text,
	`client2_legal_name` text,
	`client2_entity_type` text,
	`ownership_split` text,
	FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `contractors` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`project_id` integer NOT NULL,
	`contractor_type` text NOT NULL,
	`legal_name` text NOT NULL,
	`state` text,
	`entity_type` text,
	`address` text,
	`city` text,
	`state_address` text,
	`zip` text,
	`license_number` text,
	`license_state` text,
	`license_expiration` text,
	`contact_name` text,
	`contact_email` text,
	`contact_phone` text,
	`bond_amount` integer,
	`insurance_amount` integer,
	`insurance_expiration` text,
	`insurance_carrier` text,
	`is_active` integer DEFAULT true,
	FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `contracts` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`project_id` integer NOT NULL,
	`contract_type` text NOT NULL,
	`version` integer DEFAULT 1,
	`status` text DEFAULT 'Draft',
	`generated_at` text DEFAULT 'CURRENT_TIMESTAMP',
	`generated_by` text,
	`template_version` text,
	`file_path` text,
	`file_name` text,
	`file_hash` text,
	`variables_snapshot` text,
	`sent_at` text,
	`sent_to` text,
	`executed_at` text,
	`executed_file_path` text,
	`notes` text,
	FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `erp_field_mappings` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`variable_name` text NOT NULL,
	`variable_description` text,
	`variable_category` text,
	`odoo_model` text,
	`odoo_field` text,
	`odoo_related_field` text,
	`transform_function` text,
	`default_value` text,
	`is_required` integer DEFAULT false,
	`validation_regex` text,
	`is_active` integer DEFAULT true,
	`last_synced_at` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `erp_field_mappings_variable_name_unique` ON `erp_field_mappings` (`variable_name`);--> statement-breakpoint
CREATE TABLE `financials` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`project_id` integer NOT NULL,
	`design_fee` integer,
	`design_revision_rounds` integer DEFAULT 3,
	`design_revision_cost_overage` integer,
	`prelim_offsite` integer,
	`prelim_onsite` integer,
	`prelim_contract_price` integer,
	`home_base_price` integer,
	`home_customizations` integer DEFAULT 0,
	`final_offsite` integer,
	`refined_onsite` integer,
	`final_contract_price` integer,
	`is_locked` integer DEFAULT false,
	`locked_at` text,
	`locked_by` text,
	`inflation_trigger_date` text,
	`inflation_adjustment_percent` real DEFAULT 5,
	`material_increase_threshold` real DEFAULT 10,
	`liquidated_damages_per_day` integer,
	`liquidated_damages_cap` integer,
	`onsite_liquidated_damages_per_day` integer,
	`onsite_liquidated_damages_cap` integer,
	FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `milestones` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`project_id` integer NOT NULL,
	`milestone_type` text NOT NULL,
	`milestone_number` integer NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`percentage` real,
	`amount` integer,
	`due_upon` text,
	`target_date` text,
	`completed_date` text,
	`status` text DEFAULT 'Pending',
	`paid_date` text,
	`paid_amount` integer,
	`invoice_number` text,
	`notes` text,
	FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `project_details` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`project_id` integer NOT NULL,
	`delivery_address` text,
	`delivery_city` text,
	`delivery_state` text,
	`delivery_zip` text,
	`delivery_county` text,
	`delivery_apn` text,
	`site_acreage` text,
	`site_zoning` text,
	`home_model` text,
	`home_sq_ft` integer,
	`home_bedrooms` integer,
	`home_bathrooms` real,
	`home_stories` integer,
	`home_garage` text,
	`total_units` integer DEFAULT 1,
	`module_count` integer,
	`building_code_reference` text,
	`climate_zone` text,
	`wind_speed` text,
	`snow_load` text,
	`seismic_zone` text,
	`agreement_execution_date` text,
	`design_start_date` text,
	`design_complete_date` text,
	`green_light_date` text,
	`production_start_date` text,
	`estimated_delivery_date` text,
	`actual_delivery_date` text,
	`governing_law_state` text,
	`arbitration_location` text,
	FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `projects` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`project_number` text NOT NULL,
	`name` text NOT NULL,
	`status` text DEFAULT 'Draft' NOT NULL,
	`state` text,
	`on_site_selection` text DEFAULT 'CRC',
	`odoo_project_id` integer,
	`created_at` text DEFAULT 'CURRENT_TIMESTAMP',
	`updated_at` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `projects_project_number_unique` ON `projects` (`project_number`);--> statement-breakpoint
CREATE TABLE `warranty_terms` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`project_id` integer NOT NULL,
	`dvele_fit_finish_months` integer DEFAULT 12,
	`dvele_structural_months` integer DEFAULT 120,
	`dvele_systems_months` integer DEFAULT 24,
	`dvele_building_envelope_months` integer DEFAULT 60,
	`onsite_fit_finish_months` integer DEFAULT 12,
	`onsite_structural_months` integer DEFAULT 120,
	`onsite_systems_months` integer DEFAULT 24,
	`client_fit_finish_months` integer DEFAULT 12,
	`client_structural_months` integer DEFAULT 120,
	`client_building_envelope_months` integer DEFAULT 60,
	`custom_warranty_terms` text,
	`warranty_start_date` text,
	FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action
);
